## DO NOT EDIT! GENERATED AUTOMATICALLY!
## Process this file with automake to produce Makefile.in.
# Copyright (C) 2002-2010 Free Software Foundation, Inc.
#
# This file is free software, distributed under the terms of the GNU
# General Public License.  As a special exception to the GNU General
# Public License, this file may be distributed as part of a program
# that contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.

AUTOMAKE_OPTIONS = 1.5 foreign

SUBDIRS =
TESTS =
XFAIL_TESTS =
TESTS_ENVIRONMENT =
noinst_PROGRAMS =
check_PROGRAMS =
noinst_HEADERS =
noinst_LIBRARIES =
check_LIBRARIES = libtests.a
EXTRA_DIST =
BUILT_SOURCES =
SUFFIXES =
MOSTLYCLEANFILES = core *.stackdump
MOSTLYCLEANDIRS =
CLEANFILES =
DISTCLEANFILES =
MAINTAINERCLEANFILES =

AM_CPPFLAGS = \
  -I. -I$(srcdir) \
  -I.. -I$(srcdir)/.. \
  -I../lib -I$(srcdir)/../lib

LDADD = libtests.a ../lib/libm4.a libtests.a $(LIBTESTS_LIBDEPS)

libtests_a_SOURCES =
libtests_a_LIBADD = $(M4tests_LIBOBJS)
libtests_a_DEPENDENCIES = $(M4tests_LIBOBJS)
EXTRA_libtests_a_SOURCES =
AM_LIBTOOLFLAGS = --preserve-dup-deps

TESTS_ENVIRONMENT += EXEEXT='@EXEEXT@' srcdir='$(srcdir)'

## begin gnulib module alloca-opt-tests

TESTS += test-alloca-opt
check_PROGRAMS += test-alloca-opt

EXTRA_DIST += test-alloca-opt.c

## end   gnulib module alloca-opt-tests

## begin gnulib module arg-nonnull

# The BUILT_SOURCES created by this Makefile snippet are not used via #include
# statements but through direct file reference. Therefore this snippet must be
# present in all Makefile.am that need it. This is ensured by the applicability
# 'all' defined above.

BUILT_SOURCES += arg-nonnull.h
# The arg-nonnull.h that gets inserted into generated .h files is the same as
# build-aux/arg-nonnull.h, except that it has the copyright header cut off.
arg-nonnull.h: $(top_srcdir)/build-aux/arg-nonnull.h
	$(AM_V_GEN)rm -f $@-t $@ && \
	sed -n -e '/GL_ARG_NONNULL/,$$p' \
	  < $(top_srcdir)/build-aux/arg-nonnull.h \
	  > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += arg-nonnull.h arg-nonnull.h-t

ARG_NONNULL_H=arg-nonnull.h

EXTRA_DIST += $(top_srcdir)/build-aux/arg-nonnull.h

## end   gnulib module arg-nonnull

## begin gnulib module array-list

libtests_a_SOURCES += gl_array_list.h gl_array_list.c

## end   gnulib module array-list

## begin gnulib module array-list-tests

TESTS += test-array_list
check_PROGRAMS += test-array_list

EXTRA_DIST += test-array_list.c macros.h

## end   gnulib module array-list-tests

## begin gnulib module array-oset

libtests_a_SOURCES += gl_array_oset.h gl_array_oset.c

## end   gnulib module array-oset

## begin gnulib module array-oset-tests

TESTS += test-array_oset
check_PROGRAMS += test-array_oset
test_array_oset_LDADD = $(LDADD) @LIBINTL@

EXTRA_DIST += test-array_oset.c macros.h

## end   gnulib module array-oset-tests

## begin gnulib module avltree-oset-tests

TESTS += test-avltree_oset
check_PROGRAMS += test-avltree_oset
EXTRA_DIST += test-avltree_oset.c macros.h

## end   gnulib module avltree-oset-tests

## begin gnulib module binary-io-tests

TESTS += test-binary-io.sh
check_PROGRAMS += test-binary-io

EXTRA_DIST += test-binary-io.sh test-binary-io.c macros.h

## end   gnulib module binary-io-tests

## begin gnulib module btowc-tests

TESTS += test-btowc1.sh test-btowc2.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-btowc

EXTRA_DIST += test-btowc1.sh test-btowc2.sh test-btowc.c signature.h macros.h

## end   gnulib module btowc-tests

## begin gnulib module c-ctype-tests

TESTS += test-c-ctype
check_PROGRAMS += test-c-ctype

EXTRA_DIST += test-c-ctype.c macros.h

## end   gnulib module c-ctype-tests

## begin gnulib module c-stack-tests

TESTS += test-c-stack.sh test-c-stack2.sh
TESTS_ENVIRONMENT += LIBSIGSEGV='@LIBSIGSEGV@'
check_PROGRAMS += test-c-stack
test_c_stack_LDADD = $(LDADD) $(LIBCSTACK) @LIBINTL@
MOSTLYCLEANFILES += t-c-stack.tmp t-c-stack2.tmp
EXTRA_DIST += test-c-stack.c test-c-stack.sh test-c-stack2.sh macros.h

## end   gnulib module c-stack-tests

## begin gnulib module c-strcase

libtests_a_SOURCES += c-strcase.h c-strcasecmp.c c-strncasecmp.c

## end   gnulib module c-strcase

## begin gnulib module c-strcase-tests

TESTS += test-c-strcase.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_TR_UTF8='@LOCALE_TR_UTF8@'
check_PROGRAMS += test-c-strcasecmp test-c-strncasecmp
EXTRA_DIST += test-c-strcase.sh test-c-strcasecmp.c test-c-strncasecmp.c macros.h

## end   gnulib module c-strcase-tests

## begin gnulib module cloexec-tests

TESTS += test-cloexec
check_PROGRAMS += test-cloexec
EXTRA_DIST += test-cloexec.c macros.h

## end   gnulib module cloexec-tests

## begin gnulib module closein-tests

TESTS += test-closein.sh
check_PROGRAMS += test-closein
test_closein_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-closein.sh test-closein.c

## end   gnulib module closein-tests

## begin gnulib module dirname-tests

TESTS += test-dirname
check_PROGRAMS += test-dirname
test_dirname_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-dirname.c

## end   gnulib module dirname-tests

## begin gnulib module dup2-tests

TESTS += test-dup2
check_PROGRAMS += test-dup2
EXTRA_DIST += test-dup2.c signature.h macros.h

## end   gnulib module dup2-tests

## begin gnulib module environ-tests

TESTS += test-environ
check_PROGRAMS += test-environ

EXTRA_DIST += test-environ.c

## end   gnulib module environ-tests

## begin gnulib module errno-tests

TESTS += test-errno
check_PROGRAMS += test-errno

EXTRA_DIST += test-errno.c

## end   gnulib module errno-tests

## begin gnulib module fcntl-h-tests

TESTS += test-fcntl-h
check_PROGRAMS += test-fcntl-h
EXTRA_DIST += test-fcntl-h.c

## end   gnulib module fcntl-h-tests

## begin gnulib module fcntl-tests

TESTS += test-fcntl
check_PROGRAMS += test-fcntl
EXTRA_DIST += test-fcntl.c signature.h macros.h

## end   gnulib module fcntl-tests

## begin gnulib module fflush-tests

TESTS += test-fflush test-fflush2.sh
check_PROGRAMS += test-fflush test-fflush2
MOSTLYCLEANFILES += test-fflush.txt
EXTRA_DIST += test-fflush.c test-fflush2.sh test-fflush2.c signature.h macros.h

## end   gnulib module fflush-tests

## begin gnulib module filenamecat-tests

TESTS += test-filenamecat
check_PROGRAMS += test-filenamecat
test_filenamecat_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-filenamecat.c

## end   gnulib module filenamecat-tests

## begin gnulib module fopen-safer-tests

TESTS += test-fopen-safer
check_PROGRAMS += test-fopen-safer
EXTRA_DIST += test-fopen.h test-fopen-safer.c macros.h

## end   gnulib module fopen-safer-tests

## begin gnulib module fopen-tests

TESTS += test-fopen
check_PROGRAMS += test-fopen

EXTRA_DIST += test-fopen.h test-fopen.c signature.h macros.h

## end   gnulib module fopen-tests

## begin gnulib module fpending-tests

TESTS += test-fpending.sh
check_PROGRAMS += test-fpending
MOSTLYCLEANFILES += test-fpending.t
EXTRA_DIST += test-fpending.c test-fpending.sh macros.h

## end   gnulib module fpending-tests

## begin gnulib module fpurge-tests

TESTS += test-fpurge
check_PROGRAMS += test-fpurge
MOSTLYCLEANFILES += t-fpurge.tmp
EXTRA_DIST += test-fpurge.c macros.h

## end   gnulib module fpurge-tests

## begin gnulib module freadahead-tests

TESTS += test-freadahead.sh
check_PROGRAMS += test-freadahead
EXTRA_DIST += test-freadahead.c test-freadahead.sh macros.h

## end   gnulib module freadahead-tests

## begin gnulib module freading-tests

TESTS += test-freading
check_PROGRAMS += test-freading
MOSTLYCLEANFILES += t-freading.tmp
EXTRA_DIST += test-freading.c macros.h

## end   gnulib module freading-tests

## begin gnulib module frexp-nolibm-tests

TESTS += test-frexp-nolibm
check_PROGRAMS += test-frexp-nolibm
test_frexp_nolibm_SOURCES = test-frexp.c
EXTRA_DIST += test-frexp.c signature.h macros.h

## end   gnulib module frexp-nolibm-tests

## begin gnulib module frexpl-nolibm-tests

TESTS += test-frexpl-nolibm
check_PROGRAMS += test-frexpl-nolibm
test_frexpl_nolibm_SOURCES = test-frexpl.c
EXTRA_DIST += test-frexpl.c signature.h macros.h

## end   gnulib module frexpl-nolibm-tests

## begin gnulib module fseeko-tests

TESTS += test-fseeko.sh test-fseeko2.sh
check_PROGRAMS += test-fseeko
EXTRA_DIST += test-fseeko.c test-fseeko.sh test-fseeko2.sh signature.h macros.h

## end   gnulib module fseeko-tests

## begin gnulib module ftello-tests

TESTS += test-ftello.sh test-ftello2.sh
check_PROGRAMS += test-ftello
EXTRA_DIST += test-ftello.c test-ftello.sh test-ftello2.sh signature.h macros.h

## end   gnulib module ftello-tests

## begin gnulib module getdtablesize-tests

TESTS += test-getdtablesize
check_PROGRAMS += test-getdtablesize
EXTRA_DIST += test-getdtablesize.c signature.h macros.h

## end   gnulib module getdtablesize-tests

## begin gnulib module getopt-posix-tests

TESTS += test-getopt
check_PROGRAMS += test-getopt
test_getopt_LDADD = $(LDADD) $(LIBINTL)
EXTRA_DIST += macros.h signature.h test-getopt.c test-getopt.h test-getopt_long.h

## end   gnulib module getopt-posix-tests

## begin gnulib module getpagesize


EXTRA_DIST += getpagesize.c

EXTRA_libtests_a_SOURCES += getpagesize.c

## end   gnulib module getpagesize

## begin gnulib module gettext

# This is for those projects which use "gettextize --intl" to put a source-code
# copy of libintl into their package. In such projects, every Makefile.am needs
# -I$(top_builddir)/intl, so that <libintl.h> can be found in this directory.
# For the Makefile.ams in other directories it is the maintainer's
# responsibility; for the one from gnulib we do it here.
# This option has no effect when the user disables NLS (because then the intl
# directory contains no libintl.h file) or when the project does not use
# "gettextize --intl".
AM_CPPFLAGS += -I$(top_builddir)/intl

EXTRA_DIST += $(top_srcdir)/build-aux/config.rpath

## end   gnulib module gettext

## begin gnulib module gettimeofday-tests

TESTS += test-gettimeofday
check_PROGRAMS += test-gettimeofday

EXTRA_DIST += signature.h test-gettimeofday.c

## end   gnulib module gettimeofday-tests

## begin gnulib module isnand-nolibm-tests

TESTS += test-isnand-nolibm
check_PROGRAMS += test-isnand-nolibm

EXTRA_DIST += test-isnand-nolibm.c test-isnand.h nan.h macros.h

## end   gnulib module isnand-nolibm-tests

## begin gnulib module isnanf-nolibm-tests

TESTS += test-isnanf-nolibm
check_PROGRAMS += test-isnanf-nolibm

EXTRA_DIST += test-isnanf-nolibm.c test-isnanf.h nan.h macros.h

## end   gnulib module isnanf-nolibm-tests

## begin gnulib module isnanl-nolibm-tests

TESTS += test-isnanl-nolibm
check_PROGRAMS += test-isnanl-nolibm

EXTRA_DIST += test-isnanl-nolibm.c test-isnanl.h nan.h macros.h

## end   gnulib module isnanl-nolibm-tests

## begin gnulib module langinfo-tests

TESTS += test-langinfo
check_PROGRAMS += test-langinfo
EXTRA_DIST += test-langinfo.c

## end   gnulib module langinfo-tests

## begin gnulib module linkedhash-list-tests

TESTS += test-linkedhash_list
check_PROGRAMS += test-linkedhash_list
EXTRA_DIST += test-linkedhash_list.c macros.h

## end   gnulib module linkedhash-list-tests

## begin gnulib module lseek-tests

TESTS += test-lseek.sh
check_PROGRAMS += test-lseek
EXTRA_DIST += test-lseek.c test-lseek.sh signature.h macros.h

## end   gnulib module lseek-tests

## begin gnulib module lstat-tests

TESTS += test-lstat
check_PROGRAMS += test-lstat
EXTRA_DIST += test-lstat.h test-lstat.c signature.h macros.h

## end   gnulib module lstat-tests

## begin gnulib module malloca-tests

TESTS += test-malloca
check_PROGRAMS += test-malloca

EXTRA_DIST += test-malloca.c

## end   gnulib module malloca-tests

## begin gnulib module math-tests

TESTS += test-math
check_PROGRAMS += test-math
EXTRA_DIST += test-math.c

## end   gnulib module math-tests

## begin gnulib module mbrtowc-tests

TESTS += test-mbrtowc1.sh test-mbrtowc2.sh test-mbrtowc3.sh test-mbrtowc4.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-mbrtowc

EXTRA_DIST += test-mbrtowc1.sh test-mbrtowc2.sh test-mbrtowc3.sh test-mbrtowc4.sh test-mbrtowc.c signature.h macros.h

## end   gnulib module mbrtowc-tests

## begin gnulib module mbsinit-tests

TESTS += test-mbsinit.sh
TESTS_ENVIRONMENT += LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-mbsinit

EXTRA_DIST += test-mbsinit.sh test-mbsinit.c signature.h macros.h

## end   gnulib module mbsinit-tests

## begin gnulib module memchr-tests

TESTS += test-memchr
check_PROGRAMS += test-memchr
EXTRA_DIST += test-memchr.c zerosize-ptr.h signature.h macros.h

## end   gnulib module memchr-tests

## begin gnulib module memchr2-tests

TESTS += test-memchr2
check_PROGRAMS += test-memchr2
EXTRA_DIST += test-memchr2.c zerosize-ptr.h macros.h

## end   gnulib module memchr2-tests

## begin gnulib module nl_langinfo-tests

TESTS += test-nl_langinfo.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-nl_langinfo
EXTRA_DIST += test-nl_langinfo.sh test-nl_langinfo.c signature.h macros.h

## end   gnulib module nl_langinfo-tests

## begin gnulib module open-tests

TESTS += test-open
check_PROGRAMS += test-open
EXTRA_DIST += test-open.h test-open.c signature.h macros.h

## end   gnulib module open-tests

## begin gnulib module pipe-tests

TESTS += test-pipe.sh
check_PROGRAMS += test-pipe
test_pipe_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-pipe.sh test-pipe.c macros.h

## end   gnulib module pipe-tests

## begin gnulib module pipe2-tests

TESTS += test-pipe2
check_PROGRAMS += test-pipe2
EXTRA_DIST += test-pipe2.c signature.h macros.h

## end   gnulib module pipe2-tests

## begin gnulib module posix_spawnp-tests

if POSIX_SPAWN_PORTED
TESTS += test-posix_spawn1 test-posix_spawn2
check_PROGRAMS += test-posix_spawn1 test-posix_spawn2

BUILT_SOURCES += test-posix_spawn1.sh
test-posix_spawn1.sh: test-posix_spawn1.in.sh
	$(AM_V_GEN)rm -f $@-t $@ && \
	cp $(srcdir)/test-posix_spawn1.in.sh $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += test-posix_spawn1.sh test-posix_spawn1.sh-t

BUILT_SOURCES += test-posix_spawn2.sh
test-posix_spawn2.sh: test-posix_spawn2.in.sh
	$(AM_V_GEN)rm -f $@-t $@ && \
	cp $(srcdir)/test-posix_spawn2.in.sh $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += test-posix_spawn2.sh test-posix_spawn2.sh-t
endif
EXTRA_DIST += test-posix_spawn1.c test-posix_spawn1.in.sh test-posix_spawn2.c test-posix_spawn2.in.sh signature.h

## end   gnulib module posix_spawnp-tests

## begin gnulib module printf-frexp-tests

TESTS += test-printf-frexp
check_PROGRAMS += test-printf-frexp
EXTRA_DIST += test-printf-frexp.c macros.h

## end   gnulib module printf-frexp-tests

## begin gnulib module printf-frexpl-tests

TESTS += test-printf-frexpl
check_PROGRAMS += test-printf-frexpl
EXTRA_DIST += test-printf-frexpl.c macros.h

## end   gnulib module printf-frexpl-tests

## begin gnulib module putenv


EXTRA_DIST += putenv.c

EXTRA_libtests_a_SOURCES += putenv.c

## end   gnulib module putenv

## begin gnulib module quotearg-tests

TESTS += test-quotearg.sh
TESTS_ENVIRONMENT += LOCALE_FR='@LOCALE_FR@' LOCALE_FR_UTF8='@LOCALE_FR_UTF8@'
check_PROGRAMS += test-quotearg
test_quotearg_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-quotearg.sh test-quotearg.c macros.h locale/fr/LC_MESSAGES/test-quotearg.po locale/fr/LC_MESSAGES/test-quotearg.mo

## end   gnulib module quotearg-tests

## begin gnulib module rawmemchr-tests

TESTS += test-rawmemchr
check_PROGRAMS += test-rawmemchr
EXTRA_DIST += test-rawmemchr.c signature.h macros.h

## end   gnulib module rawmemchr-tests

## begin gnulib module rmdir-tests

TESTS += test-rmdir
check_PROGRAMS += test-rmdir
EXTRA_DIST += test-rmdir.h test-rmdir.c signature.h macros.h

## end   gnulib module rmdir-tests

## begin gnulib module same-inode


EXTRA_DIST += same-inode.h

## end   gnulib module same-inode

## begin gnulib module sched-tests

TESTS += test-sched
check_PROGRAMS += test-sched
EXTRA_DIST += test-sched.c

## end   gnulib module sched-tests

## begin gnulib module setenv


EXTRA_DIST += setenv.c

EXTRA_libtests_a_SOURCES += setenv.c

## end   gnulib module setenv

## begin gnulib module setenv-tests

TESTS += test-setenv
check_PROGRAMS += test-setenv
EXTRA_DIST += test-setenv.c signature.h macros.h

## end   gnulib module setenv-tests

## begin gnulib module sigaction-tests

TESTS += test-sigaction
check_PROGRAMS += test-sigaction
EXTRA_DIST += test-sigaction.c signature.h macros.h

## end   gnulib module sigaction-tests

## begin gnulib module signal-tests

TESTS += test-signal
check_PROGRAMS += test-signal
EXTRA_DIST += test-signal.c

## end   gnulib module signal-tests

## begin gnulib module signbit-tests

TESTS += test-signbit
check_PROGRAMS += test-signbit

EXTRA_DIST += test-signbit.c macros.h

## end   gnulib module signbit-tests

## begin gnulib module snprintf-tests

TESTS += test-snprintf
check_PROGRAMS += test-snprintf

EXTRA_DIST += test-snprintf.c signature.h macros.h

## end   gnulib module snprintf-tests

## begin gnulib module spawn-tests

TESTS += test-spawn
check_PROGRAMS += test-spawn
EXTRA_DIST += test-spawn.c

## end   gnulib module spawn-tests

## begin gnulib module stat-tests

TESTS += test-stat
check_PROGRAMS += test-stat
EXTRA_DIST += test-stat.h test-stat.c signature.h macros.h

## end   gnulib module stat-tests

## begin gnulib module stdbool-tests

TESTS += test-stdbool
check_PROGRAMS += test-stdbool
EXTRA_DIST += test-stdbool.c

## end   gnulib module stdbool-tests

## begin gnulib module stddef-tests

TESTS += test-stddef
check_PROGRAMS += test-stddef
EXTRA_DIST += test-stddef.c

## end   gnulib module stddef-tests

## begin gnulib module stdint-tests

TESTS += test-stdint
check_PROGRAMS += test-stdint
EXTRA_DIST += test-stdint.c

## end   gnulib module stdint-tests

## begin gnulib module stdio-tests

TESTS += test-stdio
check_PROGRAMS += test-stdio
EXTRA_DIST += test-stdio.c

## end   gnulib module stdio-tests

## begin gnulib module stdlib-tests

TESTS += test-stdlib
check_PROGRAMS += test-stdlib
EXTRA_DIST += test-stdlib.c

## end   gnulib module stdlib-tests

## begin gnulib module strchrnul-tests

TESTS += test-strchrnul
check_PROGRAMS += test-strchrnul
EXTRA_DIST += test-strchrnul.c signature.h macros.h

## end   gnulib module strchrnul-tests

## begin gnulib module strerror-tests

TESTS += test-strerror
check_PROGRAMS += test-strerror
EXTRA_DIST += test-strerror.c signature.h macros.h

## end   gnulib module strerror-tests

## begin gnulib module string-tests

TESTS += test-string
check_PROGRAMS += test-string
EXTRA_DIST += test-string.c

## end   gnulib module string-tests

## begin gnulib module strsignal-tests

TESTS += test-strsignal
check_PROGRAMS += test-strsignal
test_strsignal_LDADD = $(LDADD) @LIBINTL@ $(LIBTHREAD)
EXTRA_DIST += test-strsignal.c signature.h macros.h

## end   gnulib module strsignal-tests

## begin gnulib module strstr-tests

TESTS += test-strstr
check_PROGRAMS += test-strstr
EXTRA_DIST += test-strstr.c zerosize-ptr.h signature.h macros.h

## end   gnulib module strstr-tests

## begin gnulib module strtod-tests

LIBS += $(POW_LIB)
TESTS += test-strtod
check_PROGRAMS += test-strtod
EXTRA_DIST += test-strtod.c signature.h macros.h

## end   gnulib module strtod-tests

## begin gnulib module symlink


EXTRA_DIST += symlink.c

EXTRA_libtests_a_SOURCES += symlink.c

## end   gnulib module symlink

## begin gnulib module symlink-tests

TESTS += test-symlink
check_PROGRAMS += test-symlink
EXTRA_DIST += test-symlink.h test-symlink.c signature.h macros.h

## end   gnulib module symlink-tests

## begin gnulib module sys_stat-tests

TESTS += test-sys_stat
check_PROGRAMS += test-sys_stat
EXTRA_DIST += test-sys_stat.c

## end   gnulib module sys_stat-tests

## begin gnulib module sys_time-tests

TESTS += test-sys_time
check_PROGRAMS += test-sys_time
EXTRA_DIST += test-sys_time.c

## end   gnulib module sys_time-tests

## begin gnulib module sys_wait-tests

TESTS += test-sys_wait
check_PROGRAMS += test-sys_wait
EXTRA_DIST += test-sys_wait.c

## end   gnulib module sys_wait-tests

## begin gnulib module time-tests

TESTS += test-time
check_PROGRAMS += test-time
EXTRA_DIST += test-time.c

## end   gnulib module time-tests

## begin gnulib module unistd-safer-tests

TESTS += test-dup-safer
check_PROGRAMS += test-dup-safer
EXTRA_DIST += test-dup-safer.c macros.h

## end   gnulib module unistd-safer-tests

## begin gnulib module unistd-tests

TESTS += test-unistd
check_PROGRAMS += test-unistd
EXTRA_DIST += test-unistd.c

## end   gnulib module unistd-tests

## begin gnulib module unsetenv


EXTRA_DIST += unsetenv.c

EXTRA_libtests_a_SOURCES += unsetenv.c

## end   gnulib module unsetenv

## begin gnulib module unsetenv-tests

TESTS += test-unsetenv
check_PROGRAMS += test-unsetenv
EXTRA_DIST += test-unsetenv.c signature.h macros.h

## end   gnulib module unsetenv-tests

## begin gnulib module update-copyright-tests

TESTS += test-update-copyright.sh
TESTS_ENVIRONMENT += PATH='$(abs_aux_dir)'$(PATH_SEPARATOR)"$$PATH"
EXTRA_DIST += test-update-copyright.sh

## end   gnulib module update-copyright-tests

## begin gnulib module vasnprintf-tests

TESTS += test-vasnprintf
check_PROGRAMS += test-vasnprintf

EXTRA_DIST += test-vasnprintf.c macros.h

## end   gnulib module vasnprintf-tests

## begin gnulib module vasprintf-posix-tests

TESTS += test-vasprintf-posix
check_PROGRAMS += test-vasprintf-posix

EXTRA_DIST += test-vasprintf-posix.c nan.h macros.h

## end   gnulib module vasprintf-posix-tests

## begin gnulib module vasprintf-tests

TESTS += test-vasprintf
check_PROGRAMS += test-vasprintf

EXTRA_DIST += test-vasprintf.c signature.h macros.h

## end   gnulib module vasprintf-tests

## begin gnulib module vc-list-files-tests

TESTS += test-vc-list-files-git.sh
TESTS += test-vc-list-files-cvs.sh
TESTS_ENVIRONMENT += PATH='$(abs_aux_dir)'$(PATH_SEPARATOR)"$$PATH"
EXTRA_DIST += test-vc-list-files-git.sh test-vc-list-files-cvs.sh

## end   gnulib module vc-list-files-tests

## begin gnulib module version-etc-tests

TESTS += test-version-etc.sh
check_PROGRAMS += test-version-etc
test_version_etc_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-version-etc.c test-version-etc.sh

## end   gnulib module version-etc-tests

## begin gnulib module warn-on-use

BUILT_SOURCES += warn-on-use.h
# The warn-on-use.h that gets inserted into generated .h files is the same as
# build-aux/warn-on-use.h, except that it has the copyright header cut off.
warn-on-use.h: $(top_srcdir)/build-aux/warn-on-use.h
	$(AM_V_GEN)rm -f $@-t $@ && \
	sed -n -e '/^.ifndef/,$$p' \
	  < $(top_srcdir)/build-aux/warn-on-use.h \
	  > $@-t && \
	mv $@-t $@
MOSTLYCLEANFILES += warn-on-use.h warn-on-use.h-t

WARN_ON_USE_H=warn-on-use.h

EXTRA_DIST += $(top_srcdir)/build-aux/warn-on-use.h

## end   gnulib module warn-on-use

## begin gnulib module wchar-tests

TESTS += test-wchar
check_PROGRAMS += test-wchar
EXTRA_DIST += test-wchar.c

## end   gnulib module wchar-tests

## begin gnulib module wcrtomb-tests

TESTS += test-wcrtomb.sh
TESTS_ENVIRONMENT += \
  LOCALE_FR='@LOCALE_FR@' \
  LOCALE_FR_UTF8='@LOCALE_FR_UTF8@' \
  LOCALE_JA='@LOCALE_JA@' \
  LOCALE_ZH_CN='@LOCALE_ZH_CN@'
check_PROGRAMS += test-wcrtomb

EXTRA_DIST += test-wcrtomb.sh test-wcrtomb.c signature.h macros.h

## end   gnulib module wcrtomb-tests

## begin gnulib module wctob


EXTRA_DIST += wctob.c

EXTRA_libtests_a_SOURCES += wctob.c

## end   gnulib module wctob

## begin gnulib module wctype-tests

TESTS += test-wctype
check_PROGRAMS += test-wctype
EXTRA_DIST += test-wctype.c macros.h

## end   gnulib module wctype-tests

## begin gnulib module xalloc-die-tests

TESTS += test-xalloc-die.sh
check_PROGRAMS += test-xalloc-die
test_xalloc_die_LDADD = $(LDADD) @LIBINTL@
EXTRA_DIST += test-xalloc-die.c test-xalloc-die.sh init.sh

## end   gnulib module xalloc-die-tests

## begin gnulib module xvasprintf-tests

TESTS += test-xvasprintf
check_PROGRAMS += test-xvasprintf
test_xvasprintf_LDADD = $(LDADD) @LIBINTL@

EXTRA_DIST += test-xvasprintf.c macros.h

## end   gnulib module xvasprintf-tests

# Clean up after Solaris cc.
clean-local:
	rm -rf SunWS_cache

mostlyclean-local: mostlyclean-generic
	@for dir in '' $(MOSTLYCLEANDIRS); do \
	  if test -n "$$dir" && test -d $$dir; then \
	    echo "rmdir $$dir"; rmdir $$dir; \
	  fi; \
	done; \
	:
